# Generated by Django 4.0.3 on 2022-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.TextField()),
                ('PH', models.TextField()),
                ('Soil', models.TextField()),
                ('Nitrate', models.TextField()),
                ('Turbidity', models.TextField()),
                ('Image', models.TextField()),
                ('Online', models.BooleanField(default=False)),
            ],
        ),
    ]
